name: chatbot
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.1
  stacked_services: ^1.1.0
  cupertino_icons: null
  flutter_native_splash: null
  google_fonts: null
  rename: null
  timeago: null
  url_launcher: null
  figma_squircle: null
  logger: null
  auto_size_text: null 
  dio: null
 #  http: ^1.1.2
  pdf: null
  path_provider: null
  printing: null


dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mockito: ^5.4.3
  stacked_generator: ^1.5.1
  flutter_launcher_icons: null

# change splash color and logo here
flutter_native_splash:
  color: "#00BCD4"
  color_dark: "#00BCD4"
  image: assets/images/logo_foreground.png
  image_dark: assets/images/logo_foreground.png
  #android_gravity: fill # for fullscreen splash image
  #ios_content_mode: scaleAspectFill # for fullscreen splash image
  web_image_mode: center
  android_12:
    image: assets/images/logo_foreground.png
    icon_background_color: "#00BCD4"

# change app logo here
flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
  windows:
    generate: true
  web:
    generate: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#00BCD4"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"

flutter:
  uses-material-design: true
  # add assets and fonts here
  assets:
    - assets/images/
    - assets/anim/
